import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { forkJoin } from 'rxjs';
import { ApiService } from '../../core/api/api.service';
import { Categoria, Produto, ProdutoRequest, UnidadeMedida, UnidadeMedidaInfo, VariacaoProduto } from '../../core/models/api.models';
import { mensagemErro } from '../../core/utils/erro-api';

@Component({ selector: 'lnf-produtos', imports: [FormsModule, RouterLink], template: `
<div class="container page-section"><a routerLink="/cadastros" class="back-link"><i class="bi bi-arrow-left me-2"></i>Cadastros</a><div class="d-flex justify-content-between align-items-center my-4"><div><span class="eyebrow">Cadastro</span><h1 class="h2 mb-0">Produtos</h1></div><button class="btn btn-primary" (click)="novo()"><i class="bi bi-plus-lg me-2"></i>Novo</button></div>
@if (erro()) { <div class="alert alert-danger">{{ erro() }}</div> }<input class="form-control mb-3" placeholder="Pesquisar produto" [(ngModel)]="busca" (ngModelChange)="carregarProdutos()">
@if (editando()) { <form class="card p-3 mb-4" (ngSubmit)="salvarProduto()"><h2 class="h5">{{ produtoId ? 'Editar produto' : 'Novo produto' }}</h2><div class="row g-3"><div class="col-12 col-md-6"><label class="form-label">Nome</label><input class="form-control" required maxlength="150" [(ngModel)]="modelo.nome" name="nome"></div><div class="col-12 col-md-6"><label class="form-label">Categoria</label><select class="form-select" required [(ngModel)]="modelo.categoria_id" name="categoria"><option value="">Selecione</option>@for (c of categorias(); track c.id) { <option [value]="c.id">{{ c.nome }}</option> }</select></div><div class="col-12"><div class="form-check"><input id="unidades" class="form-check-input" type="checkbox" [(ngModel)]="modelo.tratar_apenas_como_unidades" name="unidades" (ngModelChange)="ajustarTipo()"><label for="unidades" class="form-check-label">Tratar apenas como unidades</label></div>@if (!modelo.tratar_apenas_como_unidades) { <div class="form-check mt-2"><input id="variacoes" class="form-check-input" type="checkbox" [(ngModel)]="modelo.contem_variacoes" name="variacoes"><label for="variacoes" class="form-check-label">Contém variações de peso ou volume</label></div><label class="form-label mt-3">Unidade de medida</label><select class="form-select" [(ngModel)]="modelo.unidade_medida" name="medida" required>@for (u of unidades(); track u.codigo) { <option [value]="u.codigo">{{ u.descricao }} ({{ u.codigo }})</option> }</select> }</div><div class="col-12"><div class="form-check"><input id="sem-marca" class="form-check-input" type="checkbox" [(ngModel)]="modelo.nao_solicitar_marca" name="semMarca"><label for="sem-marca" class="form-check-label">Não solicitar marca</label></div></div><div class="col-12 d-flex gap-2"><button class="btn btn-primary" [disabled]="salvando() || !valido()">Salvar</button><button type="button" class="btn btn-outline-secondary" (click)="cancelar()">Cancelar</button></div></div></form> }
<div class="d-grid gap-3">@for (produto of produtos(); track produto.id) { <article class="card p-3"><div class="d-flex justify-content-between gap-3"><div><strong>{{ produto.nome }}</strong><div class="text-secondary small">{{ produto.categoria.nome }} · {{ produto.tratar_apenas_como_unidades ? 'somente unidades' : produto.unidade_medida }}{{ produto.contem_variacoes ? ' · com variações' : '' }}{{ produto.nao_solicitar_marca ? ' · sem marca' : '' }}</div></div><div class="d-flex gap-2"><button class="btn btn-sm btn-outline-secondary" (click)="editar(produto)"><i class="bi bi-pencil"></i></button>@if (produto.contem_variacoes) { <button class="btn btn-sm btn-outline-primary" (click)="abrirVariacoes(produto)">Variações</button> }</div></div>
@if (produtoVariacoes()?.id === produto.id) { <div class="border-top mt-3 pt-3"><div class="d-flex justify-content-between"><h3 class="h6">Variações</h3><button class="btn btn-sm btn-primary" (click)="novaVariacao()">Adicionar</button></div>@if (editandoVariacao()) { <div class="row g-2 mt-1"><div class="col-4"><input type="number" min="0.000001" step="any" class="form-control" placeholder="Quantidade" [(ngModel)]="variacaoQuantidade"></div><div class="col-3"><select class="form-select" [(ngModel)]="variacaoUnidade">@for (u of unidades(); track u.codigo) { <option [value]="u.codigo">{{ u.codigo }}</option> }</select></div><div class="col-5"><input class="form-control" placeholder="Descrição opcional" [(ngModel)]="variacaoDescricao"></div><div class="col-12 d-flex gap-2"><button class="btn btn-sm btn-primary" (click)="salvarVariacao()">Salvar</button><button class="btn btn-sm btn-outline-secondary" (click)="editandoVariacao.set(false)">Cancelar</button></div></div> }<div class="list-group list-group-flush mt-2">@for (v of variacoes(); track v.id) { <button class="list-group-item list-group-item-action d-flex justify-content-between" (click)="editarVariacao(v)"><span>{{ v.nome_exibicao }}</span><i class="bi bi-pencil"></i></button> } @empty { <small class="text-secondary">Nenhuma variação cadastrada.</small> }</div></div> }
 </article> } @empty { <p class="text-center text-secondary py-5">Nenhum produto encontrado.</p> }</div></div>` })
export class Produtos implements OnInit {
  private api = inject(ApiService); readonly produtos = signal<Produto[]>([]); readonly categorias = signal<Categoria[]>([]); readonly unidades = signal<UnidadeMedidaInfo[]>([]); readonly variacoes = signal<VariacaoProduto[]>([]); readonly erro = signal<string | null>(null); readonly editando = signal(false); readonly salvando = signal(false); readonly produtoVariacoes = signal<Produto | null>(null); readonly editandoVariacao = signal(false);
  busca = ''; produtoId: string | null = null; variacaoId: string | null = null; variacaoQuantidade: number | null = null; variacaoUnidade: UnidadeMedida = 'G'; variacaoDescricao = '';
  modelo: ProdutoRequest = this.modeloVazio();
  ngOnInit(): void { forkJoin({ categorias: this.api.listarCategorias(), unidades: this.api.listarUnidadesMedida() }).subscribe({ next: (x) => { this.categorias.set(x.categorias); this.unidades.set(x.unidades); }, error: (e) => this.erro.set(mensagemErro(e)) }); this.carregarProdutos(); }
  carregarProdutos(): void { this.api.listarProdutos(this.busca).subscribe({ next: (x) => this.produtos.set(x), error: (e) => this.erro.set(mensagemErro(e)) }); }
  novo(): void { this.produtoId = null; this.modelo = this.modeloVazio(); this.editando.set(true); }
  editar(p: Produto): void { this.produtoId = p.id; this.modelo = { nome: p.nome, categoria_id: p.categoria.id, nao_solicitar_marca: p.nao_solicitar_marca, tratar_apenas_como_unidades: p.tratar_apenas_como_unidades, contem_variacoes: p.contem_variacoes, unidade_medida: p.unidade_medida }; this.editando.set(true); }
  cancelar(): void { this.editando.set(false); }
  ajustarTipo(): void { if (this.modelo.tratar_apenas_como_unidades) { this.modelo.contem_variacoes = false; this.modelo.unidade_medida = null; } else if (!this.modelo.unidade_medida) this.modelo.unidade_medida = 'KG'; }
  valido(): boolean { return !!this.modelo.nome.trim() && !!this.modelo.categoria_id && (this.modelo.tratar_apenas_como_unidades || !!this.modelo.unidade_medida); }
  salvarProduto(): void { if (!this.valido()) return; this.salvando.set(true); const req = this.produtoId ? this.api.atualizarProduto(this.produtoId, this.modelo) : this.api.criarProduto(this.modelo); req.subscribe({ next: () => { this.salvando.set(false); this.editando.set(false); this.carregarProdutos(); }, error: (e) => { this.salvando.set(false); this.erro.set(mensagemErro(e)); } }); }
  abrirVariacoes(p: Produto): void { this.produtoVariacoes.set(p); this.api.listarVariacoes(p.id).subscribe({ next: (x) => this.variacoes.set(x), error: (e) => this.erro.set(mensagemErro(e)) }); }
  novaVariacao(): void { this.variacaoId = null; this.variacaoQuantidade = null; this.variacaoUnidade = 'G'; this.variacaoDescricao = ''; this.editandoVariacao.set(true); }
  editarVariacao(v: VariacaoProduto): void { this.variacaoId = v.id; this.variacaoQuantidade = Number(v.quantidade); this.variacaoUnidade = v.unidade_medida; this.variacaoDescricao = v.descricao ?? ''; this.editandoVariacao.set(true); }
  salvarVariacao(): void { const p = this.produtoVariacoes(); if (!p || !this.variacaoQuantidade || this.variacaoQuantidade <= 0) return; const valor = { quantidade: this.variacaoQuantidade, unidade_medida: this.variacaoUnidade, descricao: this.variacaoDescricao.trim() || null }; const req = this.variacaoId ? this.api.atualizarVariacao(p.id, this.variacaoId, valor) : this.api.criarVariacao(p.id, valor); req.subscribe({ next: () => { this.editandoVariacao.set(false); this.abrirVariacoes(p); }, error: (e) => this.erro.set(mensagemErro(e)) }); }
  private modeloVazio(): ProdutoRequest { return { nome: '', categoria_id: '', nao_solicitar_marca: false, tratar_apenas_como_unidades: false, contem_variacoes: false, unidade_medida: 'KG' }; }
}
